In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
import sklearn

from pandas import Series, DataFrame
from pylab import rcParams
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics 
from sklearn.metrics import classification_report


# Se carga el dataset
datos = pd.read_csv("dataset-prueba2-mod.csv")
datos.head(5)

Muestra 1  Muestra 2  Muestra 3  Muestra 4  Muestra 5  Muestra 6  \
0       26.0        4.0        5.0        8.0       -1.0      -13.0   
1      -47.0       -6.0       -5.0       -7.0       13.0       -1.0   
2      -19.0       -8.0       -8.0       -8.0      -21.0       -6.0   
3        2.0        3.0        0.0        2.0        0.0       22.0   
4        6.0        0.0        0.0       -2.0      -14.0       10.0   

   Muestra 7  Muestra 8  Muestra 9  Muestra 10    ...      Muestra 56  \
0     -109.0      -66.0       -9.0         2.0    ...           -28.0   
1       35.0      -10.0       10.0        -4.0    ...           -25.0   
2      -79.0       12.0        0.0         5.0    ...           -83.0   
3      106.0      -14.0      -16.0        -2.0    ...           -38.0   
4      -51.0        5.0        7.0         0.0    ...            38.0   

   Muestra 57  Muestra 58  Muestra 59  Muestra 60  Muestra 61  Muestra 62  \
0        61.0         4.0         8.0         5.0         4.0        -7.0   
1        47.0         6.0         6.0         5.0        13.0        21.0   
2         7.0         7.0         1.0        -8.0         7.0        21.0   
3       -11.0         4.0         7.0        11.0        33.0        39.0   
4       -35.0        -8.0         2.0         6.0       -13.0       -24.0   

   Muestra 63  Muestra 64  resultado  
0       -59.0        16.0          0  
1       111.0        15.0          0  
2       114.0        48.0          0  
3       119.0        43.0          0  
4      -112.0       -69.0          0  

[5 rows x 65 columns]

In [2]:
#Se comprueba la información del dataset
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8756 entries, 0 to 8755
Data columns (total 65 columns):
Muestra 1     8756 non-null float64
Muestra 2     8756 non-null float64
Muestra 3     8756 non-null float64
Muestra 4     8756 non-null float64
Muestra 5     8756 non-null float64
Muestra 6     8756 non-null float64
Muestra 7     8756 non-null float64
Muestra 8     8756 non-null float64
Muestra 9     8756 non-null float64
Muestra 10    8756 non-null float64
Muestra 11    8756 non-null float64
Muestra 12    8756 non-null float64
Muestra 13    8756 non-null float64
Muestra 14    8756 non-null float64
Muestra 15    8756 non-null float64
Muestra 16    8756 non-null float64
Muestra 17    8756 non-null float64
Muestra 18    8756 non-null float64
Muestra 19    8756 non-null float64
Muestra 20    8756 non-null float64
Muestra 21    8756 non-null float64
Muestra 22    8756 non-null float64
Muestra 23    8756 non-null float64
Muestra 24    8756 non-null float64
Muestra 25    8756 non-null f

In [3]:
#Se comprueba cuantos valores nulos existen
datos.isnull().sum()

Muestra 1     0
Muestra 2     0
Muestra 3     0
Muestra 4     0
Muestra 5     0
Muestra 6     0
Muestra 7     0
Muestra 8     0
Muestra 9     0
Muestra 10    0
Muestra 11    0
Muestra 12    0
Muestra 13    0
Muestra 14    0
Muestra 15    0
Muestra 16    0
Muestra 17    0
Muestra 18    0
Muestra 19    0
Muestra 20    0
Muestra 21    0
Muestra 22    0
Muestra 23    0
Muestra 24    0
Muestra 25    0
Muestra 26    0
Muestra 27    0
Muestra 28    0
Muestra 29    0
Muestra 30    0
             ..
Muestra 36    0
Muestra 37    0
Muestra 38    0
Muestra 39    0
Muestra 40    0
Muestra 41    0
Muestra 42    0
Muestra 43    0
Muestra 44    0
Muestra 45    0
Muestra 46    0
Muestra 47    0
Muestra 48    0
Muestra 49    0
Muestra 50    0
Muestra 51    0
Muestra 52    0
Muestra 53    0
Muestra 54    0
Muestra 55    0
Muestra 56    0
Muestra 57    0
Muestra 58    0
Muestra 59    0
Muestra 60    0
Muestra 61    0
Muestra 62    0
Muestra 63    0
Muestra 64    0
resultado     0
Length: 65, dtype: int64

In [4]:
#Al no haber valores nulos, se prosigue en el workflow

#Seleccionamos la variable que queremos predecir
yy=datos['resultado']
datos=datos.drop(['resultado'],1)

In [5]:
#Obtenemos dummies para datos categorizables, si es que existen
datos=pd.get_dummies(datos)

In [6]:
datos.head()

Muestra 1  Muestra 2  Muestra 3  Muestra 4  Muestra 5  Muestra 6  \
0       26.0        4.0        5.0        8.0       -1.0      -13.0   
1      -47.0       -6.0       -5.0       -7.0       13.0       -1.0   
2      -19.0       -8.0       -8.0       -8.0      -21.0       -6.0   
3        2.0        3.0        0.0        2.0        0.0       22.0   
4        6.0        0.0        0.0       -2.0      -14.0       10.0   

   Muestra 7  Muestra 8  Muestra 9  Muestra 10     ...      Muestra 55  \
0     -109.0      -66.0       -9.0         2.0     ...            21.0   
1       35.0      -10.0       10.0        -4.0     ...          -105.0   
2      -79.0       12.0        0.0         5.0     ...          -128.0   
3      106.0      -14.0      -16.0        -2.0     ...           -54.0   
4      -51.0        5.0        7.0         0.0     ...            60.0   

   Muestra 56  Muestra 57  Muestra 58  Muestra 59  Muestra 60  Muestra 61  \
0       -28.0        61.0         4.0         8.0         5.0         4.0   
1       -25.0        47.0         6.0         6.0         5.0        13.0   
2       -83.0         7.0         7.0         1.0        -8.0         7.0   
3       -38.0       -11.0         4.0         7.0        11.0        33.0   
4        38.0       -35.0        -8.0         2.0         6.0       -13.0   

   Muestra 62  Muestra 63  Muestra 64  
0        -7.0       -59.0        16.0  
1        21.0       111.0        15.0  
2        21.0       114.0        48.0  
3        39.0       119.0        43.0  
4       -24.0      -112.0       -69.0  

[5 rows x 64 columns]

In [7]:
#Seleccionamos los features
X = datos.iloc[0:len(datos),0:64]
#Seleccionamos nuevamente la variable a predecir
y = yy

In [8]:
#Modelo de Árbol de decisión
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3, random_state=25)

from sklearn import tree
#Entrenamiento del algoritmo
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)

In [9]:
#Predicciones
y_pred = clf.predict(X_test)
#Evaluación del rendimiento del clasificador
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
#Print de la matriz de confusión
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))
#Print de precisión y recall

[[785  16  89]
 [  8 748  92]
 [ 68  86 735]]
              precision    recall  f1-score   support

           0       0.91      0.88      0.90       890
           1       0.88      0.88      0.88       848
           2       0.80      0.83      0.81       889

   micro avg       0.86      0.86      0.86      2627
   macro avg       0.86      0.86      0.86      2627
weighted avg       0.86      0.86      0.86      2627



In [10]:
#Modelo de Regresion logistica

from sklearn.linear_model import LogisticRegression

#Aprendizaje del algoritmo
LogReg = LogisticRegression()
LogReg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [11]:
#Predicciones
y_pred = LogReg.predict(X_test)
#Evaluación del rendimiento del clasificador
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
#Print de la matriz de confusión
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

[[401 240 249]
 [112 372 364]
 [175 340 374]]
              precision    recall  f1-score   support

           0       0.58      0.45      0.51       890
           1       0.39      0.44      0.41       848
           2       0.38      0.42      0.40       889

   micro avg       0.44      0.44      0.44      2627
   macro avg       0.45      0.44      0.44      2627
weighted avg       0.45      0.44      0.44      2627



In [12]:
#Modelo de Random Forest

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=15)
clf = clf.fit(X_train, y_train)

#Predicciones
y_pred = clf.predict(X_test)
y_prob = clf.predict_proba(X_test)
#Evaluación del rendimiento del clasificador
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
#Print de la matriz de confusión
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))
#Print de precisión y recall

[[872   2  16]
 [  1 802  45]
 [ 44  19 826]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.97       890
           1       0.97      0.95      0.96       848
           2       0.93      0.93      0.93       889

   micro avg       0.95      0.95      0.95      2627
   macro avg       0.95      0.95      0.95      2627
weighted avg       0.95      0.95      0.95      2627

